config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope :admin do
    devise_for :admins, controllers: { sessions: 'admin/admins/sessions' }
  end

  namespace :admin do
    root 'main#index'

    resources :teachers, except: :show
    resources :disciplines, except: :show

    resources :courses, except: :show do
      resources :lessons, except: :show
    end

    resources :lessons, only: [] do
      post :sort, on: :collection
    end

    namespace :api do
      namespace :lessons do
        resource :mass_update, only: :create
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/shared/_main_menu.html.slim
nav.navbar.navbar-expand-lg.bg-light.navbar_color
  = link_to 'OnSchool', admin_root_path, class: 'navbar-brand'
  - if current_admin
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        - @main_menu.each do |item, options|
          li.nav-link class=(options[:active] ? 'active' : '')
            = link_to options[:path] do
              = options[:name]
              - if options[:active]
                span.sr-only (current)
      ul.navbar-nav.mr-auto
        li.nav-item
          a.nav-link.waves-effect.waves-light
            i.fab.fa-facebook-f
        li.nav-item
          a.nav-link.waves-effect.waves-light
            i.fab.fa-instagram
        li.nav-item
          li.nav-item
            a.nav-link.waves-effect.waves-light
              i.fab.fa-twitter
        li.nav-item
          a.nav-link.waves-effect.waves-light
            i.fab.fa-google-plus-g
      ul.navbar-nav.text-right
        li.nav-item.dropdown
          a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | #{current_admin.first_name} #{current_admin.last_name}
          .dropdown-menu.navbar_color aria-labelledby="navbarDropdown"
            a.dropdown-item
              = link_to 'Вийти', destroy_admin_session_path, method: :delete